import './globals.css'

import ThemeRegistry from './ThemeRegistry/ThemeRegistry'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeRegistry>
        <body  >{children}</body>
      </ThemeRegistry>
    </html>
  )
}
