import { Footer } from './Components/Footer';
import './globals.css'
import Navbar from './LocalNavbar'
import ThemeRegistry from './ThemeRegistry/ThemeRegistry'
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

    <html lang="en" className={inter.className}>
      <body style={{ textDecoration: 'none' }}  >
        <ThemeRegistry>
          <Navbar />
          {children}
          <Footer />
        </ThemeRegistry>
      </body>
    </html>
  )
}
